language: scala
jdk: openjdk8
before_install:
  - git fetch --tags
stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork
jobs:
  include:
    # stage="test" if no stage is specified
    - name: test
      script: sbt scripted
    - name: formatting
      script: sbt scalafmtCheckAll scalafmtSbtCheck
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release
